spring:
  application:
    name: langchain-start

logging:
  level:
#    org.springframework.ai.chat.client.advisor: DEBUG
    com.cjy: DEBUG

langchain4j:
  open-ai:
    chat-model:
      api-key: ${DASHSCOPE_API_KEY}
      model-name: qwen-plus
      temperature: 1.0
      log-requests: true
      log-responses: true
      base-url: https://dashscope.aliyuncs.com/compatible-mode/v1

